{
 "title": "SDK Metrics (Java)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   { "name": "Namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "WorkflowType" },
   { "name": "Taskqueue", "query": { "query": "label_values(task_queue)" } }
  ]
 },
 "panels": [
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Workflow Task Schedule To Start Latency - temporal_workflow_task_schedule_to_start_latency_seconds_bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, task_queue) (rate(temporal_workflow_task_schedule_to_start_latency_seconds_bucket{task_queue=~\"$Taskqueue\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Activity Schedule To Start Latency P99 - temporal_activity_schedule_to_start_latency_seconds_bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, task_queue) (rate(temporal_activity_schedule_to_start_latency_seconds_bucket{task_queue=~\"$Taskqueue\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Workflow End to End Latency P99 - temporal_workflow_endtoend_latency_seconds_bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, task_queue) (rate(temporal_workflow_endtoend_latency_seconds_bucket{task_queue=~\"$Taskqueue\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Workflow End to End Latency (Max) - temporal_workflow_endtoend_latency_seconds_bucket",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, task_queue) (rate(temporal_workflow_endtoend_latency_seconds_bucket{task_queue=~\"$Taskqueue\"}[$__rate_interval])))",
     "legendFormat": "{{task_queue}}"
    }
   ]
  },
  {
   "title": "Workflow Task Execution Latency - temporal_workflow_task_execution_latency_seconds_bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, task_queue) (rate(temporal_workflow_task_execution_latency_seconds_bucket{task_queue=~\"$Taskqueue\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Activity Execution Latency P99 - temporal_activity_execution_latency_seconds_bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, task_queue) (rate(temporal_activity_execution_latency_seconds_bucket{task_queue=~\"$Taskqueue\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Activity End to End Latency P99 - temporal_activity_endtoend_latency_seconds_bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, task_queue) (rate(temporal_activity_succeed_endtoend_latency_seconds_bucket{task_queue=~\"$Taskqueue\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Activity End to End Latency (Max) - temporal_activity_endtoend_latency_seconds_bucket",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, task_queue) (rate(temporal_activity_succeed_endtoend_latency_seconds_bucket{task_queue=~\"$Taskqueue\"}[$__rate_interval])))",
     "legendFormat": "{{task_queue}}"
    }
   ]
  },
  { "title": "Compute", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Workflow Execution Slots Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by(task_queue) (temporal_worker_task_slots_available{worker_type=\"WorkflowWorker\"})"
    }
   ]
  },
  {
   "title": "Activity Slots Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "targets": [
    {
     "expr": "sum by(task_queue) (temporal_worker_task_slots_available{worker_type=\"ActivityWorker\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "targets": [
    { "expr": "process_cpu_usage" }
   ]
  },
  {
   "title": "Max Workflow Slots",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by(worker_type) (temporal_worker_task_slots_available{worker_type=\"WorkflowWorker\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Activity Slots",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by(worker_type) (temporal_worker_task_slots_available{worker_type=\"ActivityWorker\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Polled Workflow Tasks Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(operation, task_queue) (rate(temporal_long_request_total{operation=\"PollWorkflowTaskQueue\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Polled Activity Tasks Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(operation, task_queue) (rate(temporal_long_request_total{operation=\"PollActivityTaskQueue\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Failures (inc. RPS Limit)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(operation, status_code) (rate(temporal_long_request_failure_total[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(operation, status_code) (rate(temporal_request_failure_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workflow Pollers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by(worker_type) (temporal_poller_start_total{worker_type=\"WorkflowWorker\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Activity Pollers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(worker_type) (temporal_poller_start_total{worker_type=\"ActivityWorker\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Long Poll Per Operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(operation) (rate(temporal_long_request_total[5s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Long Request Latency P95 - temporal_request_latency_seconds_bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(namespace, operation, le) (rate(temporal_long_request_latency_seconds_bucket[5s])))",
     "legendFormat": "{{ namespace }} - {{ operation }}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(operation, ) (rate(temporal_request_total[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(operation) (rate(temporal_long_request_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency P95 - temporal_request_latency_seconds_bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(namespace, operation, le) (rate(temporal_request_latency_seconds_bucket[$__rate_interval])))",
     "legendFormat": "{{ namespace }} - {{ operation }}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Cached Workflows - temporal_sticky_cache_size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 44 },
   "targets": [
    { "expr": "temporal_sticky_cache_size" }
   ]
  },
  {
   "title": "Sticky Cache Hit Total - temporal_sticky_cache_hit_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 44 },
   "targets": [
    {
     "expr": "rate(temporal_sticky_cache_hit_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Sticky Cache Forced Eviction - temporal_sticky_cache_total_forced_eviction_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "temporal_sticky_cache_total_forced_eviction_total"
    }
   ]
  },
  {
   "title": "Sticky Cache Miss Total - temporal_sticky_cache_miss_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 44 },
   "targets": [
    {
     "expr": "rate(temporal_sticky_cache_miss_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Heap Consumption - jvm_memory_used_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(area) (jvm_memory_used_bytes{area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Local Activity Slots Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 52 },
   "targets": [
    {
     "expr": "sum(temporal_worker_task_slots_available{worker_type=\"LocalActivityWorker\"})"
    }
   ]
  },
  {
   "title": "Replay count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "sum by(task_queue) (rate(temporal_workflow_task_replay_latency_seconds_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replay latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(temporal_workflow_task_replay_latency_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}