// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbook.proto

// Protobuf Java Version: 3.25.3
package io.temporal.samples.proto;

public interface NamespaceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.Namespace)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string jamId = 1;</code>
   * @return Whether the jamId field is set.
   */
  boolean hasJamId();
  /**
   * <code>string jamId = 1;</code>
   * @return The jamId.
   */
  java.lang.String getJamId();
  /**
   * <code>string jamId = 1;</code>
   * @return The bytes for jamId.
   */
  com.google.protobuf.ByteString
      getJamIdBytes();

  /**
   * <code>string gcpServiceAccount = 2;</code>
   * @return Whether the gcpServiceAccount field is set.
   */
  boolean hasGcpServiceAccount();
  /**
   * <code>string gcpServiceAccount = 2;</code>
   * @return The gcpServiceAccount.
   */
  java.lang.String getGcpServiceAccount();
  /**
   * <code>string gcpServiceAccount = 2;</code>
   * @return The bytes for gcpServiceAccount.
   */
  com.google.protobuf.ByteString
      getGcpServiceAccountBytes();

  io.temporal.samples.proto.Namespace.ValueCase getValueCase();
}
