// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbook.proto

// Protobuf Java Version: 3.25.3
package io.temporal.samples.protoPayload;

public interface AddressBookOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.AddressBook)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .tutorial.Person people = 1;</code>
   */
  java.util.List<io.temporal.samples.protoPayload.Person>
      getPeopleList();
  /**
   * <code>repeated .tutorial.Person people = 1;</code>
   */
  io.temporal.samples.protoPayload.Person getPeople(int index);
  /**
   * <code>repeated .tutorial.Person people = 1;</code>
   */
  int getPeopleCount();
  /**
   * <code>repeated .tutorial.Person people = 1;</code>
   */
  java.util.List<? extends io.temporal.samples.protoPayload.PersonOrBuilder>
      getPeopleOrBuilderList();
  /**
   * <code>repeated .tutorial.Person people = 1;</code>
   */
  io.temporal.samples.protoPayload.PersonOrBuilder getPeopleOrBuilder(
      int index);
}
